### ISSUE TITLE
Works only for 2 test cases. 

### ISSUE THREAD

**Issue by Deven1902** [importlogic/gfg-potd#1]
https://github.com/importlogic/gfg-potd/blame/230bbe1653fbd3884015571413903cce88f3cc4b/2023/05%20-%20May/12-05-2023.cpp#L12

the above solution doesnt pass all the test cases and cleares only the first 2 test cases.

**Comment by importlogic** [comment]
Hi, thanks for raising your concern. I have updated the code now.

Unfortunately there are many cases when GeeksforGeeks makes slight changes in the problem statement as well as the test cases. That is why the code which works for me might not work for you later.

The purpose of these videos is to make you understand the idea behind the problems so even if there are slight changes you can easily tackle them. And also when I remember I try to show in the video itself that the code is working for me at that moment. So any changes in the test cases is beyond my control.


I really appreciate your comment. Please keep letting me know if there are any such cases and I will see what I can do.
